module.exports.itemPools = [
  [
    'Crash Cove',
    'Inferno Island',
    'Coco Park',
    'Meteor Gorge',
    'Jungle Boogie',
    'Roo\'s Tubes',
    'Tiger Temple',
    'Koala Carnival',
    'Dragon Mines',
  ],
  [
    'Assembly Lane',
    'Android Alley',
    'Papu\'s Pyramid',
    'Barin Ruins',
    'Sewer Speedway',
    'Blizzard Bluff',
    'Mystery Caves',
    'Slide Coliseum',
    'Dingo Canyon',
  ],
  [
    'Tiny Arena',
    'Electron Avenue',
    'N.Gin Labs',
    'Turbo Track',
    'Twilight Tour',
    'Nina\'s Nightmare',
    'Tiny Temple',
    'Clockwork Wumpa',
    'Deep Sea Driving',
    'Megamix Mania',
  ],
  [
    'Out of Time',
    'Polar Pass',
    'Oxide Station',
    'Thunder Struck',
    'Prehistoric Playground',
    'Hot Air Skyway',
    'Cortex Castle',
    'Drive-Thru Danger',
    'Gingerbread Joyride',
  ],
];

module.exports.itemlessPools = [
  [
    'Crash Cove',
    'Inferno Island',
    'Coco Park',
    'Meteor Gorge',
    'Jungle Boogie',
    'Roo\'s Tubes',
    'Koala Carnival',
    'Blizzard Bluff',
    'Tiny Temple',
  ],
  [
    'Deep Sea Driving',
    'Tiger Temple',
    'Papu\'s Pyramid',
    'Sewer Speedway',
    'Dragon Mines',
    'Dingo Canyon',
    'Barin Ruins',
  ],
  [
    'Spyro Circuit',
    'Mystery Caves',
    'N.Gin Labs',
    'Twilight Tour',
    'Android Alley',
    'Nina\'s Nightmare',
    'Assembly Lane',
  ],
  [
    'Thunder Struck',
    'Cortex Castle',
    'Polar Pass',
    'Prehistoric Playground',
    'Electron Avenue',
    'Clockwork Wumpa',
    'Out of Time',
  ],
  [
    'Drive-Thru Danger',
    'Gingerbread Joyride',
    'Oxide Station',
    'Hot Air Skyway',
    'Turbo Track',
    'Tiny Arena',
    'Slide Coliseum',
  ],
];
