module.exports.itemPools = [
  [
    'Crash Cove',
    'Coco Park',
    'Tiger Temple',
    'Dingo Canyon',
    'Blizzard Bluff',
    'Dragon Mines',
    'Inferno Island',
    'Jungle Boogie',
    'Meteor Gorge',
    'Koala Carnival',
  ],
  [
    'Mystery Caves',
    'Sewer Speedway',
    'Papu\'s Pyramid',
    'Tiny Arena',
    'N. Gin Labs',
    'Slide Coliseum',
    'Turbo Track',
    'Android Alley',
    'Barin Ruins',
    'Assembly Lane',
    'Electron Avenue',
  ],
  [
    'Polar Pass',
    'Cortex Castle',
    'Hot Air Skyway',
    'Clockwork Wumpa',
    'Prehistoric Playground',
    'Nina\'s Nightmare',
    'Gingerbread Joyride',
    'Megamix Mania',
  ],
  [
    'Oxide Station',
    'Tiny Temple',
    'Deep Sea Driving',
    'Thunder Struck',
    'Out of Time',
    'Twilight Tour',
    'Drive-Thru Danger',
  ],
];

module.exports.battlePools = [
  [
    'Skull Rock',
    'Rocky Road',
    'Rampage Ruins',
    'Temple Turmoil',
  ],
  [
    'Nitro Court',
    'Lab Basement',
    'Frozen Frenzy',
    'Magnetic Mayhem',
  ],
  [
    'Parking Lot',
    'The North Bowl',
    'Desert Storm',
    'Terra Drome',
  ],
];

module.exports._4v4Pools = [
  [
    'Crash Cove',
    'Coco Park',
    'Blizzard Bluff',
    'Inferno Island',
    'Jungle Boogie',
    'Meteor Gorge',
    'Koala Carnival',
  ],
  [
    'Tiger Temple',
    'Papu\'s Pyramid',
    'Dingo Canyon',
    'Dragon Mines',
    'Turbo Track',
    'Slide Coliseum',
    'Barin Ruins',
  ],
  [
    'Mystery Caves',
    'Sewer Speedway',
    'Tiny Arena',
    'N. Gin Labs',
    'Android Alley',
    'Assembly Lane',
    'Electron Avenue',
  ],
  [
    'Polar Pass',
    'Cortex Castle',
    'Hot Air Skyway',
    'Clockwork Wumpa',
    'Prehistoric Playground',
    'Nina\'s Nightmare',
    'Gingerbread Joyride',
    'Megamix Mania',
  ],
  [
    'Oxide Station',
    'Tiny Temple',
    'Deep Sea Driving',
    'Thunder Struck',
    'Out of Time',
    'Twilight Tour',
    'Drive-Thru Danger',
  ],
];
